if empty(glob('~/.vim/autoload/plug.vim'))
    silent !mkdir -p $HOME/vimfiles/autoload && Invoke-WebRequest -UseBasicParsing -OutFile $HOME/vimfiles/autoload/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

au VimEnter * PlugInstall --sync | source $MYVIMRC

" Plugins
call plug#begin()
Plug 'dense-analysis/ale'
Plug 'pnevma.vim'
Plug 'LunarWatcher/auto-pairs'
call plug#end()

" Settings
syntax on            
set nu              
set tabstop=4       
set softtabstop=4   
set shiftwidth=4     

set expandtab      
set smarttab      
set smartindent    
set hidden          
set noswapfile
set incsearch       
set ignorecase      
set smartcase       
set scrolloff=8     
set colorcolumn=100 
set signcolumn=yes   
set cmdheight=2      
set updatetime=100   
set encoding=utf-8 
set splitright      
set splitbelow       
set autoread        
set termguicolors
set mouse=a          
filetype on          
filetype plugin on   
filetype indent on  

" Visual
colorscheme pnevma
